# Generated by Django 5.2.7 on 2025-10-27 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='illness',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
