# Generated by Django 5.2.7 on 2025-11-01 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_donation_options_alter_post_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
